apiVersion: v1
kind: ConfigMap
metadata:
  name: rps-config
  namespace: rps-game
  labels:
    app.kubernetes.io/name: rock-paper-scissors
data:
  # SPIFFE Trust Domain for this deployment
  TRUST_DOMAIN: "noah.inter-cloud-thi.de"
  # Workload identity path
  RPS_SPIFFE_ID: "spiffe://noah.inter-cloud-thi.de/game-server-noah"
  # Server binding
  RPS_BIND: "0.0.0.0:9002"
  RPS_MTLS: "1"
  RPS_CERT_DIR: "/app/certs"
