apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rps-game

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - spiffe-helper-configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rock-paper-scissors
      app.kubernetes.io/version: "1.0.0"
    includeSelectors: false

images:
  - name: ghcr.io/npaulat99/rock-paper-scissors
    newTag: latest
