apiVersion: v1
kind: Service
metadata:
  name: rps-game
  namespace: rps-game
  labels:
    app.kubernetes.io/name: rock-paper-scissors
spec:
  type: NodePort
  selector:
    app: rps-game
  ports:
    - name: https
      port: 9002
      targetPort: 9002
      nodePort: 30902
      protocol: TCP
