apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: rps-game
  labels:
    app.kubernetes.io/name: rock-paper-scissors
data:
  helper.conf: |
    agent_address = "/tmp/spire-agent/public/api.sock"
    cmd = ""
    cmd_args = ""
    cert_dir = "/app/certs"
    renew_signal = ""
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "svid_bundle.pem"
